config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"
  get "scheduling/show"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/settings', to: 'users#settings',      via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/showall', to: 'static_pages#showall', via: 'get'

  match '/scheduling', to: 'scheduling#show', via: 'get'
  match '/scheduling', to: 'scheduling#show', via: 'post'
  match '/scheduling', to: 'scheduling#update', via: 'post'

  match '/full_position', to: 'users#full_time_table', via: 'get'
  match '/part_position', to: 'users#part_time_table', via: 'get'
  match '/allschedule', to: 'users#allschedule', via: 'get'
  match '/calendar', to: 'users#show_calendar', via: 'get'
  match '/chng_pass', to: 'users#change_password', via: 'get'

  post '/ajax/submit'      => 'users#submit'
  post '/ajax/submit_part' => 'users#submit_part'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :submited_hours

	validates :name, presence: true , length: { minimum: 4, maximum: 50 }
	validates :email, presence: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
            uniqueness: {:case_sensitive => false}
  validates :password, :length => {minimum: 6}
  validate :l_name, presence: true
  validates :phone, presence: true, format: {with:  /\A[0-9]{10}\Z/}

  validates_confirmation_of :password,
                            if: lambda { |m| m.password.present? }

  before_create {self.admin = 'yes'}
  before_save {self.email = email.downcase}
  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  has_secure_password




  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/users_controller.rb
require 'rubygems'
require 'date'

class UsersController < ApplicationController

  def show
    @user = get_user
    @days_of_week = weekdays(1)
    @days_of_week2 = weekdays(2)
    #@schedule = [true,true,true]
	  SubmitedHour.all
    submitedHour = SubmitedHour.find_by(:week_start_date =>  getStartDate, :user_id => @user.id)
    @arr = Hash.new
    if submitedHour.nil?
      @arr['Sunday'] = false
      @arr['Monday'] = false
      @arr['Tuesday'] = false
      @arr['Wednesday'] = false
      @arr['Thursday'] = false
      @arr['Friday'] = false
      @arr['Saturday'] = false
      return
    end

    @arr = Hash.new
    @arr['Sunday'] = submitedHour.Sunday_morning
    @arr['Monday'] = submitedHour.Monday_morning
    @arr['Tuesday'] = submitedHour.Tuesday_morning
    @arr['Wednesday'] = submitedHour.Wednesday_morning
    @arr['Thursday'] = submitedHour.Thursday_morning
    @arr['Friday'] = submitedHour.Friday_morning
    @arr['Saturday'] = submitedHour.Saturday_morning

    #puts "#{@arr['Sunday']}"

  end

  def new
    @user = User.new

  end

   def edit
     @user = User.find(params[:id])
   end

   def settings
     @user = get_user
   end

    def show_calendar

    end

   def update
     @user = User.find params[:id]
     #create function that will do it
     @user.update_attribute(:name, params[:user][:name])
     @user.update_attribute(:l_name, params[:user][:l_name])
     @user.update_attribute(:phone, params[:user][:phone])
     @user.update_attribute(:email, params[:user][:email])
     @user.update_attribute(:id_number, params[:user][:id_number])
     @user.update_attribute(:position, params[:user][:position])
     @user.update_attribute(:shabat, params[:user][:shabat])
     @user.update_attribute(:admin, params[:user][:admin])
     flash[:notice] = "#{@user.name} was successfully updated."
     redirect_to showall_path
   end

    def change_password
      @user = get_user
    end

    def update_password
      @user = get_user
    end

   def create
     @user = User.new(user_params)
     if @user.save
       flash[:success] = "Welcome to the Schedule App!"
       #sign_in @user  # only Admin will add new users
       redirect_to @user
     else
       render 'new'
     end
   end

  def destroy
    User.destroy(params[:id])
    redirect_to root_path
  end

  def allschedule
    week_select = @week
    @days_of_week = weekdays(week_select)
  end

  def submit
    arr = Hash.new
    params['string'].split('$').each do |param|
      splitted = param.split('=')
      arr[splitted[0]] = splitted[1]
    end
    create_events(arr)
    puts ''

  end

  def submit_part
    arr = Hash.new
    params['string'].split('$').each do |param|
      splitted = param.split('=')
      arr[splitted[0]] = splitted[1]
    end
    create_events_for_part(arr)
  end

   private

   def user_params
     params.require(:user).permit(:name, :l_name, :phone, :email, :password,
                                  :password_confirmation, :id_number, :position, :shabat, :admin)
   end

  def check_user
    usr_id = User.find(usr_id)
    usr_check = User.find_by(remember_token: remember_token)
    if(usr_id != usr_check)
      redirect_to root_path
    end
  end

  def weekdays(week)
    t = Time.now
    t +=   (60*60*24*7) if week == 2
    ans = Hash.new
    temp_t = t.wday
    while temp_t != 0
      t -= (60*60*24)
      temp_t = t.wday
    end
    7.times do
      ans[t.wday] = t.strftime("%d/%m/%Y")
      t += (60*60*24)
    end
    ans
  end

  def create_events(parsed_string)

    hours = SubmitedHour.find_by(:week_start_date =>  getStartDate, :user_id => current_user.id)
    if (hours.nil?)
      hours = SubmitedHour.create!
      hours.user_id =  current_user.id
      hours.week_start_date= getStartDate
    end




    #parsed_string.each_with_index do |key, index|

      #case key[0]
      #  when 'Sunday'


      hours.Sunday_morning=parsed_string['Sunday']
      hours.Sunday_evening=parsed_string['Sunday']
      hours.Sunday_night=parsed_string['Sunday']



      hours.Monday_morning=parsed_string['Monday']
      hours.Monday_evening=parsed_string['Monday']
      hours.Monday_night=parsed_string['Monday']



      hours.Tuesday_morning=parsed_string['Tuesday']
      hours.Tuesday_evening=parsed_string['Tuesday']
      hours.Tuesday_night=parsed_string['Tuesday']



      hours.Wednesday_morning=parsed_string['Wednesday']
      hours.Wednesday_evening=parsed_string['Wednesday']
      hours.Wednesday_night=parsed_string['Wednesday']



      hours.Thursday_morning=parsed_string['Thursday']
      hours.Thursday_evening=parsed_string['Thursday']
      hours.Thursday_night=parsed_string['Thursday']



      hours.Friday_morning=parsed_string['Friday']
      hours.Friday_evening=parsed_string['Friday']
      hours.Friday_night=parsed_string['Friday']



      hours.Saturday_morning=parsed_string['Saturday']
      hours.Saturday_evening=parsed_string['Saturday']
      hours.Saturday_night=parsed_string['Saturday']

    hours.save!

    puts ''

  end

  def create_events_for_part(parsed_string)

    hours = SubmitedHour.find_by(:week_start_date =>  getStartDate, :user_id => current_user.id)
    if (hours.nil?)
      hours = SubmitedHour.create!
      hours.user_id =  current_user.id
      hours.week_start_date= getStartDate
    end

    hours.Sunday_morning=parsed_string['Sunday']['morning']
    hours.Sunday_evening=parsed_string['Sunday']
    hours.Sunday_night=parsed_string['Sunday']

    hours.Monday_morning=parsed_string['Monday']
    hours.Monday_evening=parsed_string['Monday']
    hours.Monday_night=parsed_string['Monday']

    hours.Tuesday_morning=parsed_string['Tuesday']
    hours.Tuesday_evening=parsed_string['Tuesday']
    hours.Tuesday_night=parsed_string['Tuesday']

    hours.Wednesday_morning=parsed_string['Wednesday']
    hours.Wednesday_evening=parsed_string['Wednesday']
    hours.Wednesday_night=parsed_string['Wednesday']

    hours.Thursday_morning=parsed_string['Thursday']
    hours.Thursday_evening=parsed_string['Thursday']
    hours.Thursday_night=parsed_string['Thursday']

    hours.Friday_morning=parsed_string['Friday']
    hours.Friday_evening=parsed_string['Friday']
    hours.Friday_night=parsed_string['Friday']

    hours.Saturday_morning=parsed_string['Saturday']
    hours.Saturday_evening=parsed_string['Saturday']
    hours.Saturday_night=parsed_string['Saturday']

    hours.save!

    puts ''

  end


    def index_to_day(index)
      case index
        when 1
          'Sunday'
        when 2
          'Monday'
        when 3
          'Tuesday'
        when 4
          'Wednesday'
        when 5
          'Thursday'
        when 6
          'Friday'
        when 7
          'Saturday'
      end
    end

    def get_user
      remember_token = User.encrypt(cookies[:remember_token])
      User.find_by(remember_token: remember_token)
    end

def getStartDate
    day = 8
    month = 6
    year = 2014

    day_start = Time.now.change({:year => year, :month => month, :day => day , :hour => 0 ,  :min => 0 ,  :sec => 0  })
    day_start
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def getClass(day)
    @arr[day]?'selectedCell':''
  end

  def week_change()
    @week = params[:w]
    cookies.permanent[:week] = @week
  end



end

app/views/users/allschedule.html.erb
<div>
  Please select shifts you can work.
</div>
</br>
<div align="center"><b>First week.</b></div>
<table id="part_time_table" style="margin: 0px auto;width: 100%;text-align: center;">
  <tr>
    <td></td>
    <td><%= @days_of_week[0] %></td>
    <td><%= @days_of_week[1] %></td>
    <td><%= @days_of_week[2] %></td>
    <td><%= @days_of_week[3] %></td>
    <td><%= @days_of_week[4] %></td>
    <td><%= @days_of_week[5] %></td>
    <td><%= @days_of_week[6] %></td>
  </tr>
  <tr>
    <td>Morning<p> 07:00 - 15:00</p></td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

   </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
  </tr>
  <tr>
    <td>Evening <p>15:00 - 23:00</p></td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
  </tr>
  <tr>
    <td>Night <p>23:00 - 07:00</p></td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
  </tr>

</table>
<br/>
<div align="center"><b>Second week.</b></div>
<table id="part_time_table" style="margin: 0px auto;width: 100%;text-align: center;">
  <tr>
    <td></td>
    <td><%= @days_of_week[0] %></td>
    <td><%= @days_of_week[1] %></td>
    <td><%= @days_of_week[2] %></td>
    <td><%= @days_of_week[3] %></td>
    <td><%= @days_of_week[4] %></td>
    <td><%= @days_of_week[5] %></td>
    <td><%= @days_of_week[6] %></td>
  </tr>
  <tr>
    <td>Morning<p> 07:00 - 15:00</p></td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
  </tr>
  <tr>
    <td>Evening <p>15:00 - 23:00</p></td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
  </tr>
  <tr>
    <td>Night <p>23:00 - 07:00</p></td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
    <td >

    </td>
  </tr>

</table>
<br/>

app/views/users/change_password.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :password %>
        <%= f.text_field :password %>

        <%= f.label :new_password, "Last name" %>
        <%= f.text_field :password %>

        <%= f.label :confirm %>
        <%= f.text_field :password %>

        <%= f.submit "Change password", class: "btn btn-large btn-primary" %>
        <%= button_to "Cancel", root_path, :class => "btn btn-large btn-primary", :method => :get  %>
    <% end %>

  </div>
</div>

app/views/users/edit.html.erb
Edit info about <%= @user.name %>:</br>

<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :l_name, "Last name" %>
    <%= f.text_field :l_name %>

    <%= f.label :id_number %>
    <%= f.text_field :id_number %>

    <%= f.label :phone, "Phone number" %>
    <%= f.text_field :phone %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :position, 'Position - full/part' %>
    <%= f.radio_button 'position', 'full' %><%= f.label :position ,'full' %>
    <%= f.radio_button 'position', 'part' %><%= f.label :position ,'part' %>

    <%= f.label :shabat, "Working on shabat or not" %>
    <%= f.radio_button 'shabat', 'yes'  %><%= f.label :shabat ,'yes' %>
    <%= f.radio_button 'shabat', 'no' %><%= f.label :shabat ,'no' %>

    <%= f.label :admin, "Is Admin" %>
    <%= f.radio_button 'admin', 'no' %><%= f.label :admin,'no' %>
    <%= f.radio_button 'admin', 'yes' %><%= f.label :admin,'yes' %>


    <%= f.submit "Save changes",  class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/full_time_table.html.erb
<div>
  Please select 6 days to work. The 7th day will be dayoff.
</div>
</br>

<div align="center"><b>First week</b></div>
<table id="full_time_table" style="margin: 0px auto;width: 60%;text-align: center;">
      <tr>
        <td><%= @days_of_week[0] %></td>
        <td><%= @days_of_week[1] %></td>
        <td><%= @days_of_week[2] %></td>
        <td><%= @days_of_week[3] %></td>
        <td><%= @days_of_week[4] %></td>
        <td><%= @days_of_week[5] %></td>
        <td><%= @days_of_week[6] %></td>
      </tr>
    <tr height='150'>
        <td onclick='changeColor(this)'>
            <%= label :some_label, "Sunday" %>
        </td>


        <td onclick='changeColor(this)' class = <%= getClass("Monday")%>>
            <%= label :some_label, "Monday" %>
        </td>


        <td onclick='changeColor(this)' class = <%= getClass("Tuesday")%>>
            <%= label :some_label, "Tuesday" %>
        </td>


        <td onclick='changeColor(this)' class = <%= getClass("Wednesday")%>>
            <%= label :some_label, "Wednesday" %>
        </td>



        <td onclick='changeColor(this)' class = <%= getClass("Thursday")%>>
            <%= label :some_label, "Thursday" %>
        </td>


        <td onclick='changeColor(this)' class = <%= getClass("Friday")%>>
            <%= label :some_label, "Friday" %>
        </td>


        <td onclick='changeColor(this)' class = <%= getClass("Saturday")%>>
            <%= label :some_label, "Saturday" %>
        </td>


</table>

<br>

<div align="center"><b>Second week.</b></div>

<table id="full_time_table2" style="margin: 0px auto;width: 60%;text-align: center;">
  <tr>
    <td><%= @days_of_week2[0] %></td>
    <td><%= @days_of_week2[1] %></td>
    <td><%= @days_of_week2[2] %></td>
    <td><%= @days_of_week2[3] %></td>
    <td><%= @days_of_week2[4] %></td>
    <td><%= @days_of_week2[5] %></td>
    <td><%= @days_of_week2[6] %></td>
  </tr>
  <tr height='150'>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Sunday" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Monday" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Tuesday" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Wednesday" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Thursday" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Friday" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Saturday" %>
    </td>
  </tr>

</table>
<br/>

<div style="text-align:center">
    <%= link_to "Submit", '#',:id => "submit_full", :onclick => "submit_full()", class: "btn btn-large btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name, "First name" %>
        <%= f.text_field :name %>

        <%= f.label :l_name, "Last name" %>
        <%= f.text_field :l_name %>

        <%= f.label :id_number %>
        <%= f.text_field :id_number %>

        <%= f.label :phone %>
        <%= f.text_field :phone %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.label :position, 'Position - full/part' %>
        <%= f.radio_button 'position', 'full', :checked => true %><%= f.label :position ,'full' %>
        <%= f.radio_button 'position', 'part' %><%= f.label :position ,'part' %>

        <%= f.label :shabat, "Working on shabat or not" %>
        <%= f.radio_button 'shabat', 'yes', :checked => true %><%= f.label :shabat ,'yes' %>
        <%= f.radio_button 'shabat', 'no' %><%= f.label :shabat ,'no' %>


        <%= f.submit "Create new user", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/part_time_table.html.erb
<div>
  Please select shifts you can work.
</div>
</br>
<div align="center"><b>First week.</b></div>
<table id="part_time_table" style="margin: 0px auto;width: 90%;text-align: center;">
  <tr>
    <td><%= @days_of_week[0] %></td>
    <td><%= @days_of_week[1] %></td>
    <td><%= @days_of_week[2] %></td>
    <td><%= @days_of_week[3] %></td>
    <td><%= @days_of_week[4] %></td>
    <td><%= @days_of_week[5] %></td>
    <td><%= @days_of_week[6] %></td>
  </tr>
  <tr>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Sunday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Monday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Tuesday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Wednesday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Thursday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Friday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Saturday morning" %>
    </td>
  </tr>
  <tr>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Sunday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Monday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Tuesday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Wednesday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Thursday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Friday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Saturday evening" %>
    </td>
  </tr>
  <tr>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Sunday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Monday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Tuesday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Wednesday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Thursday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Friday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Saturday night" %>
    </td>
  </tr>
</table>
<br/>
<div align="center"><b>Second week.</b></div>
<table id="part_time_table2" style="margin: 0px auto;width: 90%;text-align: center;">
  <tr>
    <td><%= @days_of_week2[0] %></td>
    <td><%= @days_of_week2[1] %></td>
    <td><%= @days_of_week2[2] %></td>
    <td><%= @days_of_week2[3] %></td>
    <td><%= @days_of_week2[4] %></td>
    <td><%= @days_of_week2[5] %></td>
    <td><%= @days_of_week2[6] %></td>
  </tr>
  <tr>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Sunday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Monday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Tuesday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Wednesday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Thursday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Friday morning" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Saturday morning" %>
    </td>
  </tr>
  <tr>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Sunday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Monday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Tuesday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Wednesday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Thursday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Friday evening" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Saturday evening" %>
    </td>
  </tr>
  <tr>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Sunday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Monday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Tuesday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Wednesday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Thursday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Friday night" %>
    </td>
    <td onclick='changeColor(this)'>
      <%= label :some_label, "Saturday night" %>
    </td>
  </tr>

</table>

<br/>

<div style="text-align:center">
  <%= link_to "Submit", '#', :onclick => "submit_part()", class: "btn btn-large btn-primary" %>
</div>

app/views/users/settings.html.erb
<table>
  <tr>
    <th>Name:</th>    <th><%= @user.name %></br></th>
  </tr>
  <tr>
    <th>Last name:</th>    <th><%= @user.l_name %></br></th>
  </tr>
  <tr>
    <th>ID:</th>    <th><%= @user.id_number%></th>
  </tr>
  <tr>
    <th>Phone number:</th>    <th><%= @user.phone %></br></th>
  </tr>
  <tr>
    <th>Email:</th>    <th><%= @user.email %></th>
  </tr>
  <tr>
    <th>Position:</th>    <th><%= @user.position %></th>
  </tr>
  <tr>
    <th>Working on shabat:</th>    <th><%= @user.shabat %></th>
  </tr>
  <tr>
    <th>Admin:</th> <th><%= @user.admin %></th>
  </tr>
</table>

<%= link_to 'Change password', chng_pass_path %>

app/views/users/show.html.erb
<% @user.name %> <% @user.email %>


<% if @user.position == 'full' %>
    <%= render :file => 'users/full_time_table.html.erb' %>
<% else %>
    <%= render :file => 'users/part_time_table.html.erb' %>
<% end %>

app/views/users/show_calendar.html.erb
<div align="center">
  View all shifts.
</div>