config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"
  get "scheduling/show"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/settings', to: 'users#settings',      via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/showall', to: 'static_pages#showall', via: 'get'

  match '/scheduling', to: 'scheduling#show', via: 'get'
  match '/scheduling', to: 'scheduling#show', via: 'post'
  match '/scheduling', to: 'scheduling#update', via: 'post'

  match '/full_position', to: 'users#full_time_table', via: 'get'
  match '/part_position', to: 'users#part_time_table', via: 'get'
  match '/allschedule', to: 'users#allschedule', via: 'get'
  match '/calendar', to: 'users#show_calendar', via: 'get'
  match '/chng_pass', to: 'users#change_password', via: 'get'

  post '/ajax/submit'      => 'users#submit'
  post '/ajax/submit_part' => 'users#submit_part'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created by Anton Litovka and Dima Movchan revised by Reuven Yagel
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<%= stylesheet_link_tag "dialog","fullcalendar","jquery-ui","style" %>
<%= javascript_include_tag "jrails1/fullcalendar.js","jrails1/jquery-
ui.js","jrails1/gcal.js","jrails1/jrails.js","jrails1/jquery.validate.js"%>



<% if( !signed_in? && !(request.path == '/' || request.path == '/signin' ||
        request.path == '/about' ||  request.path == '/contact' ||  request.path == '/news') )%>
    <script type="text/javascript">
        window.location.href='/'
    </script>
<% end %>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Schedule app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>

          <% if signed_in? %>
              <li><%= link_to "Calendar", calendar_path %></li>
              <% if admin? %>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Admin management <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">

                      <li><%= link_to "See all requests", scheduling_path %></li>
                      <li><%= link_to "Show all Users", showall_path%></li>
                      <li><%= link_to "Add user", new_user_path %></li>
                      <li><%= link_to "Admin settings", '#' %></li>

                    </ul>
                  </li>
              <% end %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Do schedule", current_user %></li>
                  <li><%= link_to "Settings", settings_path %></li>
                  <li><%= link_to "Help", help_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>s
    </div>
  </body>
</html>